version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      -  "81:81"
    networks: 
      - notes-app
    depends_on:
      -  django
    restart: always
  django:
    build:
      context: .
    container_name: "django-cont"
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    env_file:
      -  ".env"
    ports:
      -  "8000:8000"
    networks:
      -  notes-app
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: always
    
  db:
    image: mysql
    container_name: "db_cont"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Tapash@123"
      MYSQL_DATABASE: "test_db"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notes-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always

volumes:
  mysql-data:
networks:
  notes-app:
    

